### ISSUE TITLE
Allow user to toggle dark/light mode via settings

### ISSUE THREAD

**Issue by krschacht** [allyourbot/hostedgpt#169]
### Discussed in https://github.com/the-dot-bot/hostedgpt/discussions/168

<div type='discussions-op-text'>

<sup>Originally posted by **florianfelsing** March  3, 2024</sup>
Currently the system settings determine whether users get to see our application in light mode or dark mode. 

I think it would be nice to allow them to set their preference somewhere in the settings. Personally, I like running my system in light mode, while running most of my apps in dark mode.</div>

**Comment by krschacht** [comment]
@florianfelsing just chime in on comments if you decide to tackle this one. Otherwise it’ll sit on this 1.0 list and we’ll definitely get to it.

**Comment by florianfelsing** [comment]
I'll be working on this one next @krschacht :)

**Comment by krschacht** [comment]
@florianfelsing That's great! I added a "preferences" key to the users table so you can save it in there. If you want to see how I'm currently using it, it's when you close the nav sidebar that it updates a user preference key.

My suggestion for this dark/mode setting is:

* On the settings/account page there is a form with all the other options. Somewhere on there add this new dark mode toggle thing.
* Somehow you'll want to present a nice user interaction for toggling the mode but behind the scenes it submits as `preferences[dark_mode] = ''` (or whatever you end up calling it)
* I think that immediately after submit, the change preference will necessarily go into effect so the user should (potentially) see the overall theme change right away. That will be nice confirmation, in case they made a mistake.

**Comment by krschacht** [comment]
Hi @florianfelsing, I hope you’re doing well. I was out for a week so I got a little behind on this project, but this week I’ve been catching up again and adding a bunch of new features. I wanted to check if you still thought you’d be able to help with this light/dark mode?

**Comment by jasonpaulso** [comment]
@krschacht @florianfelsing I am happy to take this up

**Comment by krschacht** [comment]
@jasonpaulso I don't think florian got a chance to start on it so go right ahead

**Comment by florianfelsing** [comment]
Thanks @jasonpaulso
