### ISSUE TITLE
Properly format code block markdown within replies (and add a copy icon)

### ISSUE THREAD

**Issue by krschacht** [allyourbot/hostedgpt#174]

**Comment by anandvc** [comment]
I came here to request exactly this feature.

Screenshot of the issue:
<img width="1268" alt="Screenshot 2024-03-23 at 3 13 36 PM" src="https://github.com/allyourbot/hostedgpt/assets/74711/ba702293-157d-41f4-b5d7-4bae94b82ccf">

**Comment by krschacht** [comment]
Yes, agreed. This issue is bugging me too. I think I’m going to do this one next.
