### ISSUE TITLE
Get the full PWA configuration done for mobile “installed”

### ISSUE THREAD

**Issue by krschacht** [allyourbot/hostedgpt#205]
The app currently works just okay on mobile browsers. We really need to create the PWA manifest and set some things like the app icon and browser details. It’s been a long time since I’ve done this so I don’t have any other guidance to provide, off the top of my head, but even just a first pass at the manifest would be an improvement.

**Comment by krschacht** [comment]
@jasonpaulso say hi on this comment thread, for some reason github doesn't let me assign an issue to you until you've commented on them.

**Comment by jasonpaulso** [comment]
👋
