### ISSUE TITLE
Conditionalizing attachment icon in composer is broken

### ISSUE THREAD

**Issue by krschacht** [allyourbot/hostedgpt#319]
GPT-3.5 is currently the one model that does not support evaluating images. The composer is conditionalized to hide that, based on the model, and you can see it's kind of working since the placeholder text is slid to the left but the icon is not disappearing:

<img width="119" alt="image" src="https://github.com/allyourbot/hostedgpt/assets/35061/776c3ea4-c914-401f-93e5-784815186cbc">

**Comment by krschacht** [comment]
@jasonpaulso Maybe this is related to recent CSS reworking? Tagging you just in case you already know. I'll eventually get around to investigating this as well.

**Comment by jasonpaulso** [comment]
I’m happy to look into this. Can you give me repro steps?On May 2, 2024, at 5:22 PM, Keith Schacht ***@***.***> wrote:﻿
@jasonpaulso Maybe this is related to recent CSS reworking? Tagging you just in case you already know. I'll eventually get around to investigating this as well.

**Comment by jasonpaulso** [comment]
I couldn’t identify a point where my changes may have caused this regression, but I have PRd a potential fix.
