### ISSUE TITLE
Visual dark-mode issue upon signup

### ISSUE THREAD

**Issue by krschacht** [allyourbot/hostedgpt#351]
@jasonpaulso I was demoing the app to someone yesterday and discovered a new dark mode issue. They had their Mac settings permanently on dark mode. They went to the sign up page and the first clue that something was wrong was that the signup page was light mode.

I know the signup/login page would ignore any user-specific settings, but I thought this page was defaulting to whatever your system was. In his case, it was not.

Then after signing up he landed in the app. It was still light mode but when he did his first chat, the conversation title and the chat message both streamed in and they were dark mode. I had him hit refresh in the browser and then the full thing worked in dark mode.

I repro'd this myself on my Mac just by following these steps. I think the root of the issue might be that the very first pages (sign up) were not matching the system's dark mode and then the rest of the pages were doing the Turbo body replacement so they didn't reset until a full refresh was issued.

**Comment by jasonpaulso** [comment]
I *think* this is something I have fixed in https://github.com/allyourbot/hostedgpt/pull/315 but I am not 100%.

**Comment by krschacht** [comment]
Oh dang, @jasonpaulso you're right! I had left one comment on that PR and then I completely forgot about it. I just made some small changes and merged in. I confirmed this issue is fixed. Thanks!!
