### ISSUE TITLE
Implement robust auth

### ISSUE THREAD

**Issue by krschacht** [AllYourBot/hostedgpt#39]
https://stevepolito.design/blog/rails-authentication-from-scratch

https://rubyonrails.org/2023/10/5/Rails-7-1-0-has-been-released

https://api.rubyonrails.org/classes/ActiveSupport/CurrentAttributes.html

**Comment by olimart** [comment]
Also https://github.com/rails/rails/issues/50446

**Comment by krschacht** [comment]
Ah yes, thanks. I know they’re planning to ship a auth generator in rails 8. I just bought a copy of the Campfire source code so I can model our auth off that since I suspect this will be the internal reference they’ll use as they’re creating this generator.
