### ISSUE TITLE
Expand LanguageModel to know two more things about every LLM: context size and if it supports tool function calling

### ISSUE THREAD

**Issue by krschacht** [AllYourBot/hostedgpt#435]
I think the function calling can just be a boolean: `supports_tools`. Inside the ai_backend's we need to make sure that a really long conversation starts skipping older messages so that the submitted payload never exceeds the context size. Maybe this attribute is simply `context_window`, that's what OpenAI and Anthropic both seems to call it.

**Comment by stephan-buckmaster** [comment]
Did you see the pull request, @krschacht ?

**Comment by krschacht** [comment]
Thanks for doing this, @stephan-buckmaster! I'm just about done giving it a review. It never hurts to give me an extra ping. :)
